"""Candidate gate for input-only held-out evaluation.

A frozen candidate is evaluated on fresh public inputs generated by a separate
process. Expected outputs remain in a separate sealed artifact and are loaded
only after candidate executions finish. This is protocol-level non-disclosure,
not OS isolation or organizational independence; promotion stays disabled.
"""
from __future__ import annotations

import hashlib
import json
import os
import secrets
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
GENERATOR = ROOT / "generator.py"
ALLOWED_ENV = ("LANG", "LC_ALL", "PATH")
FORBIDDEN_PUBLIC_FIELDS = {"expected", "stdout", "exit_code", "answer", "label", "result"}


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def freeze_candidate(candidate: Path) -> dict[str, Any]:
    if not candidate.is_file():
        raise ValueError("candidate_missing")
    return {
        "candidate_path": str(candidate),
        "candidate_sha256": sha256_file(candidate),
        "candidate_frozen_ns": time.time_ns(),
        "evaluator_pid": os.getpid(),
        "canary": secrets.token_hex(16),
    }


def generate_fresh_bundle(frozen: dict[str, Any], output_parent: Path) -> dict[str, Any]:
    bundle_dir = output_parent / f"bundle-{secrets.token_hex(6)}"
    completed = subprocess.run(
        [sys.executable, str(GENERATOR), "--output-dir", str(bundle_dir), "--canary", frozen["canary"]],
        text=True,
        capture_output=True,
        check=False,
        timeout=5.0,
    )
    if completed.returncode != 0:
        raise RuntimeError("generator_failed")
    receipt = json.loads((bundle_dir / "receipt.json").read_text(encoding="utf-8"))
    return {
        **frozen,
        "bundle_dir": str(bundle_dir),
        "public_path": str(bundle_dir / "public_inputs.json"),
        "sealed_path": str(bundle_dir / "sealed_expected.json"),
        "receipt_path": str(bundle_dir / "receipt.json"),
        "generator_pid": receipt["generator_pid"],
        "generated_ns": receipt["generated_ns"],
        "public_sha256": receipt["public_sha256"],
        "sealed_sha256": receipt["sealed_sha256"],
    }


def evaluate_input_only(transcript: dict[str, Any], timeout_seconds: float = 2.0) -> dict[str, Any]:
    reasons: list[str] = []
    observations: list[dict[str, Any]] = []
    candidate = Path(str(transcript.get("candidate_path", "")))
    public_path = Path(str(transcript.get("public_path", "")))
    sealed_path = Path(str(transcript.get("sealed_path", "")))

    if not candidate.is_file() or sha256_file(candidate) != transcript.get("candidate_sha256"):
        reasons.append("candidate_changed_or_missing")
    if transcript.get("generator_pid") == transcript.get("evaluator_pid"):
        reasons.append("generator_not_separate_process")
    if not isinstance(transcript.get("generated_ns"), int) or transcript["generated_ns"] <= transcript.get("candidate_frozen_ns", 0):
        reasons.append("generation_not_after_freeze")
    if not public_path.is_file() or sha256_file(public_path) != transcript.get("public_sha256"):
        reasons.append("public_inputs_changed_or_missing")
    if not sealed_path.is_file() or sha256_file(sealed_path) != transcript.get("sealed_sha256"):
        reasons.append("sealed_expected_changed_or_missing")
    if timeout_seconds <= 0:
        reasons.append("timeout_invalid")
    if reasons:
        return _report(reasons, observations, False)

    public = json.loads(public_path.read_text(encoding="utf-8"))
    if not isinstance(public, list) or len(public) < 3:
        reasons.append("public_fixture_set_too_small")
        public = []
    child_env = {key: os.environ[key] for key in ALLOWED_ENV if key in os.environ}
    with tempfile.TemporaryDirectory(prefix="apex-input-only-") as run_dir:
        for probe in public:
            if not isinstance(probe, dict) or FORBIDDEN_PUBLIC_FIELDS.intersection(probe):
                reasons.append("expected_data_exposed_in_public_input")
                continue
            if set(probe) != {"probe_id", "probe_type", "stdin", "custody_canary"}:
                reasons.append("public_schema_invalid")
                continue
            if probe.get("custody_canary") != transcript.get("canary"):
                reasons.append("public_canary_mismatch")
                continue
            try:
                completed = subprocess.run(
                    [sys.executable, str(candidate)],
                    input=probe["stdin"],
                    text=True,
                    capture_output=True,
                    timeout=timeout_seconds,
                    cwd=run_dir,
                    env=child_env,
                    check=False,
                )
                observations.append(
                    {
                        "probe_id": probe["probe_id"],
                        "probe_type": probe["probe_type"],
                        "observed_exit_code": completed.returncode,
                        "observed_stdout": completed.stdout,
                    }
                )
            except subprocess.TimeoutExpired:
                observations.append({"probe_id": probe["probe_id"], "timed_out": True})
                reasons.append(f"probe_timeout:{probe['probe_id']}")

    execution_finished_ns = time.time_ns()
    try:
        sealed = json.loads(sealed_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        reasons.append("sealed_expected_invalid")
        sealed = {}
    expected_map = sealed.get("expected", {}) if isinstance(sealed, dict) else {}
    if sealed.get("custody_canary") != transcript.get("canary"):
        reasons.append("sealed_canary_mismatch")
    for observation in observations:
        probe_id = observation["probe_id"]
        expected = expected_map.get(probe_id)
        if not isinstance(expected, dict):
            reasons.append(f"expected_missing:{probe_id}")
            continue
        passed = (
            observation.get("observed_exit_code") == expected.get("exit_code")
            and observation.get("observed_stdout") == expected.get("stdout")
        )
        observation["passed"] = passed
        observation.pop("observed_stdout", None)
        if not passed:
            reasons.append(f"probe_failed:{probe_id}")
    return _report(reasons, observations, True, execution_finished_ns)


def _report(
    reasons: list[str], observations: list[dict[str, Any]], sealed_loaded_after_execution: bool,
    execution_finished_ns: int | None = None,
) -> dict[str, Any]:
    decision = "candidate_verify" if not reasons else "hold"
    return {
        "decision": decision,
        "reasons": sorted(set(reasons)),
        "mechanism": "separate_process_input_only_heldout",
        "probe_count": len(observations),
        "probe_pass_count": sum(item.get("passed") is True for item in observations),
        "generator_process_distinct": True if observations else False,
        "expected_present_in_candidate_argv_env_cwd": False,
        "sealed_loaded_after_execution": sealed_loaded_after_execution,
        "execution_finished_ns": execution_finished_ns,
        "os_level_secrecy_verified": False,
        "organizational_independence_verified": False,
        "promotion_allowed": False,
        "status": "candidate_hold",
    }
